server:
  port: 7000
spring:
  application:
    name: userManage
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    password:
    jedis:
      pool:
        max-active: 8  #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    lettuce:
      shutdown-timeout: 0
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  #指明日志存放位置
logging:
  file: E://logs/${spring.application.name}-${server.port}.logs
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.tw.blog.pojo
  configuration:
    map-underscore-to-camel-case: true


