server:
  port: 7000
spring:
  application:
    name: userManage
  #数据库配置
    datasource:
      url: jdbc:mysql://localhost:3306/myblog?characterEncoding=utf8&useSSL=true
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#  redis:
#    host: 192.168.19.100
#  session:
#    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  #指明日志存放位置
logging:
  file: E://logs/${spring.application.name}-${server.port}.logs


